// Teste ponta a ponta do fluxo principal (cria 2 contas de teste).
// Uso: npm i -D playwright && npx playwright install chromium
//      BASE_URL=https://seu-app.vercel.app node scripts/e2e.mjs
// Requer 'Confirm email' DESLIGADO no Supabase (senão o cadastro pede confirmação).
import fs from 'node:fs'
import { chromium } from 'playwright'
const BASE = process.env.BASE_URL || 'http://localhost:5173'
const SHOTS = process.env.SHOTS_DIR || './e2e-shots'
fs.mkdirSync(SHOTS, { recursive: true })
const results = []
const ok = (name, cond, extra = '') => { results.push(`${cond ? 'PASS' : 'FAIL'}  ${name}${extra ? '  ' + extra : ''}`); if (!cond) process.exitCode = 1 }

const browser = await chromium.launch()
const errors = []
async function newCtx(mobile) {
  const ctx = await browser.newContext(mobile ? { viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true } : { viewport: { width: 1440, height: 900 } })
  const page = await ctx.newPage()
  page.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
  page.on('pageerror', (e) => errors.push(String(e)))
  return { ctx, page }
}
const email = `ana.${Date.now()}@fittrack.dev`

// ---------- Desktop flow ----------
let { ctx, page } = await newCtx(false)
await page.goto(BASE + '/dashboard')
await page.waitForURL('**/login')
ok('Rota protegida redireciona para /login', page.url().endsWith('/login'))
await page.screenshot({ path: `${SHOTS}/01-login-desktop.png` })

await page.click('text=Criar conta')
await page.fill('input[name=name]', 'Ana Souza')
await page.fill('input[name=email]', email)
await page.fill('input[name=password]', 'senha123')
await page.click('button:has-text("Continuar")')
await page.click('button:has-text("Criar conta")') // validation
ok('Validação do passo 2 bloqueia envio vazio', await page.isVisible('text=Informe sua idade.'))
await page.fill('input[name=age]', '24')
await page.fill('input[name=height]', '165')
await page.fill('input[name=weight]', '60,5')
await page.selectOption('select[name=goal]', 'saude')
await page.selectOption('select[name=fitness_level]', 'iniciante')
await page.screenshot({ path: `${SHOTS}/02-cadastro-desktop.png` })
await page.click('button:has-text("Criar conta")')
await page.waitForURL('**/dashboard')
await page.waitForSelector('text=Treino recomendado')
ok('Cadastro leva ao dashboard', true)
ok('Saudação com nome', await page.isVisible('h1:has-text("Ana")'))
ok('Recomendação respeita nível/objetivo', await page.isVisible('h2:has-text("Full Body Iniciante")') || await page.isVisible('h2:has-text("Core e Mobilidade")'))
await page.screenshot({ path: `${SHOTS}/03-dashboard-vazio-desktop.png`, fullPage: true })

await page.click('nav >> text=Treinos')
await page.waitForSelector('text=HIIT 20')
const cards = await page.locator('a[href^="/treinos/"]').count()
ok('Catálogo lista treinos do seed', cards >= 5, `(${cards} treinos)`)
await page.click('button[role=tab]:has-text("Avançado")')
const adv = await page.locator('a[href^="/treinos/"]').count()
ok('Filtro por nível funciona', adv === 2, `(${adv} avançados)`)
await page.click('button[role=tab]:has-text("Todos")')
await page.screenshot({ path: `${SHOTS}/04-treinos-desktop.png`, fullPage: true })

await page.click('a:has-text("Full Body Iniciante")')
await page.waitForSelector('text=Agachamento livre')
await page.click('button:has-text("Agachamento livre")')
await page.click('button:has-text("Remada com halter")')
await page.screenshot({ path: `${SHOTS}/05-treino-detalhe-desktop.png`, fullPage: true })
await page.locator('button:has-text("Concluir treino")').filter({ visible: true }).first().click()
await page.waitForSelector('text=Treino concluído!')
ok('Modal de conclusão mostra +80 XP', await page.isVisible('text=+80'))
ok('Level up exibido (0 -> 80 XP ainda nível 1)', !(await page.isVisible('text=Subiu para o nível')))
await page.waitForTimeout(600); await page.screenshot({ path: `${SHOTS}/06-conclusao-desktop.png` })
await page.click('button:has-text("Voltar ao início")')
await page.waitForURL('**/dashboard')
await page.waitForSelector('text=Atividade recente')
await page.waitForTimeout(600)
const xpText = await page.locator('main div.rounded-2xl', { has: page.locator('span.uppercase', { hasText: /^XP$/ }) }).first().innerText()
ok('Dashboard atualizou XP para 80', /XP\s*80\s*Nível 1/.test(xpText), JSON.stringify(xpText.replace(/\n/g, ' ')))
ok('Histórico no dashboard mostra o treino', await page.locator('ul >> text=Full Body Iniciante').count() > 0)

// Double submit guard
await page.goto(BASE + '/treinos/11111111-1111-4111-8111-000000000001')
await page.waitForSelector('text=Agachamento livre')
await page.locator('button:has-text("Concluir treino")').filter({ visible: true }).first().click()
await page.waitForSelector('text=acabou de concluir')
ok('Bloqueia conclusão duplicada em 60s', true)

// Second workout -> level up (80 + 140 = 220 >= 100)
await page.goto(BASE + '/treinos/11111111-1111-4111-8111-000000000006')
await page.waitForSelector('text=Burpee')
await page.locator('button:has-text("Concluir treino")').filter({ visible: true }).first().click()
await page.waitForSelector('text=Treino concluído!')
ok('Level up exibido ao passar de 100 XP', await page.isVisible('text=Subiu para o nível 2'))
await page.screenshot({ path: `${SHOTS}/07-levelup-desktop.png` })
await page.click('button:has-text("Ver progresso")')
await page.waitForURL('**/progresso')
await page.waitForSelector('text=Histórico recente')
await page.waitForTimeout(800)
ok('Progresso: 2 itens no histórico', (await page.locator('ul li').count()) === 2)
ok('Progresso: XP total 220', await page.isVisible('text=220'))
await page.screenshot({ path: `${SHOTS}/08-progresso-desktop.png`, fullPage: true })
await page.click('nav >> text=Dashboard')
await page.waitForSelector('text=Treino recomendado')
await page.waitForTimeout(800)
await page.screenshot({ path: `${SHOTS}/09-dashboard-ativo-desktop.png`, fullPage: true })

// Profile edit + session persistence
await page.click('nav >> text=Perfil')
await page.waitForSelector('text=Dados pessoais')
ok('Perfil carrega peso do cadastro (60,5)', (await page.inputValue('input[name=weight]')) === '60.5')
await page.fill('input[name=weight]', '59')
await page.selectOption('select[name=fitness_level]', 'intermediario')
await page.click('button:has-text("Salvar alterações")')
await page.waitForSelector('text=Perfil atualizado.')
await page.screenshot({ path: `${SHOTS}/10-perfil-desktop.png`, fullPage: true })
await page.reload()
await page.waitForSelector('text=Dados pessoais')
ok('Sessão persiste após reload', page.url().endsWith('/perfil'))
ok('Edição de perfil persistida', (await page.inputValue('input[name=weight]')) === '59')

// Logout
await page.click('aside >> text=Sair')
await page.waitForURL('**/login')
await page.goto(BASE + '/progresso')
await page.waitForURL('**/login')
ok('Logout encerra sessão e protege rotas', true)
await page.fill('input[name=email]', email)
await page.fill('input[name=password]', 'errada')
await page.click('button:has-text("Entrar")')
await page.waitForSelector('text=E-mail ou senha incorretos.')
ok('Login inválido mostra erro em português', true)
await page.fill('input[name=password]', 'senha123')
await page.click('button:has-text("Entrar")')
await page.waitForURL('**/progresso')
ok('Login devolve para a página originalmente pedida', true)
await page.waitForSelector('text=Histórico recente')
await page.waitForTimeout(500)
ok('Login funciona e mantém dados (220 XP)', await page.isVisible('text=220'))
await ctx.close()

// ---------- Second user (mobile): isolation ----------
;({ ctx, page } = await newCtx(true))
await page.goto(BASE + '/cadastro')
await page.screenshot({ path: `${SHOTS}/11-cadastro-mobile.png` })
await page.fill('input[name=name]', 'Bruno Lima')
await page.fill('input[name=email]', `bruno.${Date.now()}@fittrack.dev`)
await page.fill('input[name=password]', 'senha123')
await page.click('button:has-text("Continuar")')
await page.fill('input[name=age]', '31'); await page.fill('input[name=height]', '182'); await page.fill('input[name=weight]', '85')
await page.selectOption('select[name=goal]', 'ganhar_massa'); await page.selectOption('select[name=fitness_level]', 'intermediario')
await page.click('button:has-text("Criar conta")')
await page.waitForURL('**/dashboard')
await page.waitForSelector('text=Treino recomendado')
await page.waitForTimeout(600)
ok('Recomendação para ganhar massa/intermediário', await page.isVisible('h2:has-text("Costas e Bíceps")') || await page.isVisible('h2:has-text("Peito e Tríceps")'))
await page.screenshot({ path: `${SHOTS}/12-dashboard-mobile.png`, fullPage: true })
await page.locator('nav a[href="/progresso"]').filter({ visible: true }).click()
await page.waitForSelector('text=Nenhum treino ainda')
ok('Segundo usuário não vê histórico do primeiro (estado vazio)', true)
await page.screenshot({ path: `${SHOTS}/13-progresso-vazio-mobile.png`, fullPage: true })
await page.goto(BASE + '/treinos/11111111-1111-4111-8111-000000000002')
await page.waitForSelector('text=Supino reto com barra')
await page.screenshot({ path: `${SHOTS}/14-treino-mobile.png` })
await page.locator('button:has-text("Concluir treino")').filter({ visible: true }).first().click()
await page.waitForSelector('text=Treino concluído!')
await page.waitForTimeout(600); await page.screenshot({ path: `${SHOTS}/15-conclusao-mobile.png` })
await page.click('button:has-text("Voltar ao início")')
await page.goto(BASE + '/treinos')
await page.waitForSelector('text=HIIT 20')
await page.screenshot({ path: `${SHOTS}/16-treinos-mobile.png`, fullPage: true })
await page.goto(BASE + '/perfil')
await page.waitForSelector('text=Dados pessoais')
await page.screenshot({ path: `${SHOTS}/17-perfil-mobile.png`, fullPage: true })
const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
ok('Sem scroll horizontal no mobile', !overflow)
await page.goto(BASE + '/rota-inexistente')
ok('404 funciona', await page.isVisible('text=404'))
await ctx.close()
await browser.close()

const relevant = errors.filter((e) => !/favicon|fonts\.g|ERR_NAME|net::ERR|Failed to load resource/i.test(e))
ok('Sem erros de JS no console', relevant.length === 0, relevant.slice(0, 3).join(' | '))
console.log(results.join('\n'))
